name: Testing
on: push
jobs:
  check_builds:
    runs-on: ubuntu-latest
    steps:
      - name: "Build Changelog"
        id: build_changelog
        uses: unl0ck/action-automatic-releases@master
        with:
          repo_token: ${{ secrets.TOKEN }}
          automatic_release_tag: "latest"
      - name: "echo"
        run: echo ${{steps.build_changelog.outputs.release_body}}
